# Generated by Django 5.1.1 on 2024-10-03 13:58

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('trial_start_date', models.DateTimeField(verbose_name='Trial start date')),
                ('trial_end_date', models.DateTimeField(verbose_name='Trial start date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sub', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'db_table': 'Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('success', models.BooleanField(verbose_name='succeeded')),
                ('tracking_id', models.CharField(max_length=150, verbose_name='Payment Gateway Tracking ID')),
                ('status', models.CharField(max_length=150, verbose_name='Order Status')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='subscriptify.subscription', verbose_name='Subscription')),
            ],
            options={
                'db_table': 'Payments',
                'indexes': [models.Index(django.db.models.functions.datetime.TruncDate('created_at'), models.F('created_at'), name='payment_created_at_date_idx')],
            },
        ),
    ]
